#!/usr/bin/env bash
set -euo pipefail

VERSION="${1:-$(grep '^version=' module.prop | cut -d'=' -f2)}"
DIST_DIR="dist"
BIN_DIR="tailscale/bin"
MANIFEST="tailscale/binary-manifest.sh"
TAILSCALE_RELEASE_TAG="${TAILSCALE_RELEASE_TAG:-v1.98.8-android}"
JQ_RELEASE_TAG="${JQ_RELEASE_TAG:-v1.6}"
TAILSCALE_ARM_SHA256="${TAILSCALE_ARM_SHA256:-e5be9d356cb9af43d476a683100562530c64625c93ea775deef08bcc5c0b7fed}"
TAILSCALE_ARM64_SHA256="${TAILSCALE_ARM64_SHA256:-0e1545aa19b6c89a4601c9eab1f1a15a0b80be99994c569f72482f2964632198}"
JQ_ARM_SHA256="${JQ_ARM_SHA256:-f885443795bb6968e9641ec2876e9a86847ba82bdee7fd123c7d32545d474b86}"
JQ_ARM64_SHA256="${JQ_ARM64_SHA256:-100d88b043eb9286eb71f1a28fd3f7f92adca98f78796af82a738c930e57f87b}"

download() { local url="$1"; shift; curl --fail --silent --show-error --location --retry 3 --retry-all-errors --retry-delay 2 --connect-timeout 15 --max-time 180 "$url" "$@"; }
get_release_json() { download "https://api.github.com/repos/$1/releases/tags/$2"; }
sha256_file() { sha256sum "$1" | awk '{print $1}'; }
zip_dir() {
  local out="$1"; shift
  python3 - "$out" "$@" <<'PY'
import os, sys, zipfile, fnmatch
out=sys.argv[1]; excludes=sys.argv[2:]
def skip(path):
    return any(fnmatch.fnmatch(path, pat) or path.startswith(pat.rstrip('*')) for pat in excludes)
with zipfile.ZipFile(out, 'w', zipfile.ZIP_DEFLATED, compresslevel=9) as z:
    for root, dirs, files in os.walk('.'):
        dirs[:] = [d for d in dirs if not skip(os.path.relpath(os.path.join(root,d), '.') + '/')]
        for f in files:
            p=os.path.relpath(os.path.join(root,f), '.')
            if p == out or skip(p): continue
            z.write(p)
PY
}

echo "Building Magisk-Tailscaled ${VERSION}"
mkdir -p "$BIN_DIR" "$DIST_DIR"
rm -f "$BIN_DIR"/* "$MANIFEST"

command -v npm >/dev/null 2>&1 || { echo "npm is required to build the WebUI" >&2; exit 1; }
echo "Building KernelSU/APatch WebUI..."
rm -rf webroot webui/.parcel-cache
npm --prefix webui ci --registry=https://registry.npmjs.org
npm --prefix webui run typecheck
npm --prefix webui run lint
npm --prefix webui test
npm --prefix webui audit --audit-level=high --registry=https://registry.npmjs.org
tests/test-config.sh
tests/test-installer.sh
tests/test-watchdog.sh
tests/test-logs.sh
tests/test-version.sh "$VERSION"
for script in customize.sh service.sh uninstall.sh tailscale/settings.sh tailscale/scripts/*; do
  sh -n "$script"
  command -v busybox >/dev/null 2>&1 && busybox sh -n "$script"
  command -v mksh >/dev/null 2>&1 && mksh -n "$script"
done
if command -v shellcheck >/dev/null 2>&1; then
  shellcheck -s sh customize.sh service.sh uninstall.sh tailscale/settings.sh tailscale/scripts/*
fi
PROJECT_ROOT=$(pwd)
(cd webui && ./node_modules/.bin/parcel build src/index.html --dist-dir "$PROJECT_ROOT/webroot" --public-url ./ --no-source-maps)
python3 - <<'PY'
from html.parser import HTMLParser
from pathlib import Path
class Assets(HTMLParser):
    def __init__(self): super().__init__(); self.paths=[]
    def handle_starttag(self, _tag, attrs):
        for key, value in attrs:
            if key in {'src','href'} and value and not value.startswith(('http:','https:','#')):
                self.paths.append(value)
root=Path('webroot'); index=root/'index.html'
assert index.is_file(), 'missing webroot/index.html'
parser=Assets(); parser.feed(index.read_text())
missing=[path for path in parser.paths if not (root/path).is_file()]
assert not missing, f'missing WebUI assets: {missing}'
PY

TS_JSON=$(get_release_json "anasfanani/tailscale-android-cli" "$TAILSCALE_RELEASE_TAG")
JQ_JSON=$(get_release_json "theshoqanebi/jq-build-for-android" "$JQ_RELEASE_TAG")
TS_TAG=$(jq -r .tag_name <<<"$TS_JSON")
JQ_TAG=$(jq -r .tag_name <<<"$JQ_JSON")
{
  echo "# Generated by .github/tools/build.sh for reproducible lightweight installs."
  echo "TAILSCALE_RELEASE_TAG='$TS_TAG'"
  echo "JQ_RELEASE_TAG='$JQ_TAG'"
} > "$MANIFEST"

echo "Downloading and hashing binaries..."
for ARCH in arm arm64; do
  case $ARCH in arm) F_ARCH='armv7a' ;; arm64) F_ARCH='aarch64' ;; esac
  TS_URL=$(jq -r --arg pattern "tailscale_.*_${ARCH}\\.tgz" '.assets[] | select(.name | test($pattern)) | .browser_download_url' <<<"$TS_JSON" | head -1)
  JQ_URL=$(jq -r --arg pattern "jq-${F_ARCH}-linux-android" '.assets[] | select(.name | test($pattern)) | .browser_download_url' <<<"$JQ_JSON" | head -1)
  [ -n "$TS_URL" ] && [ "$TS_URL" != null ] || { echo "missing tailscale asset for $ARCH" >&2; exit 1; }
  [ -n "$JQ_URL" ] && [ "$JQ_URL" != null ] || { echo "missing jq asset for $ARCH" >&2; exit 1; }
  download "$TS_URL" -o "$DIST_DIR/tailscale-$ARCH.tgz"
  download "$JQ_URL" -o "$BIN_DIR/jq-$ARCH"
  tar -xzf "$DIST_DIR/tailscale-$ARCH.tgz" -C "$BIN_DIR" tailscaled
  mv "$BIN_DIR/tailscaled" "$BIN_DIR/tailscaled-$ARCH"
  TS_SHA=$(sha256_file "$DIST_DIR/tailscale-$ARCH.tgz")
  JQ_SHA=$(sha256_file "$BIN_DIR/jq-$ARCH")
  case $ARCH in
    arm) EXPECTED_TS_SHA=$TAILSCALE_ARM_SHA256; EXPECTED_JQ_SHA=$JQ_ARM_SHA256 ;;
    arm64) EXPECTED_TS_SHA=$TAILSCALE_ARM64_SHA256; EXPECTED_JQ_SHA=$JQ_ARM64_SHA256 ;;
  esac
  [ "$TS_SHA" = "$EXPECTED_TS_SHA" ] || { echo "tailscale $ARCH checksum mismatch" >&2; exit 1; }
  [ "$JQ_SHA" = "$EXPECTED_JQ_SHA" ] || { echo "jq $ARCH checksum mismatch" >&2; exit 1; }
  {
    echo "TAILSCALE_${ARCH}_URL='$TS_URL'"
    echo "TAILSCALE_${ARCH}_SHA256='$TS_SHA'"
    echo "JQ_${ARCH}_URL='$JQ_URL'"
    echo "JQ_${ARCH}_SHA256='$JQ_SHA'"
  } >> "$MANIFEST"
done
rm -f "$DIST_DIR"/tailscale-*.tgz

LIGHT="${DIST_DIR}/Magisk-Tailscaled-${VERSION}.zip"
FULL="${DIST_DIR}/Magisk-Tailscaled-${VERSION}-full.zip"
rm -f "$LIGHT" "$FULL"
echo "Creating lightweight zip..."
zip_dir "$LIGHT" '.git*' '.github/*' 'browser-qa/*' 'dist/*' 'tests/*' 'webui/*' '*.zip' '*.md' 'tailscale/bin/*' '.shellcheckrc' 'system/*'
echo "Creating full zip..."
zip_dir "$FULL" '.git*' '.github/*' 'browser-qa/*' 'dist/*' 'tests/*' 'webui/*' '*.zip' '*.md' '.shellcheckrc' 'system/*'
python3 - "$LIGHT" "$FULL" <<'PY'
import sys, zipfile
for archive in sys.argv[1:]:
    with zipfile.ZipFile(archive) as z:
        names=set(z.namelist())
        assert 'webroot/index.html' in names, f'{archive}: missing WebUI index'
        assert any(n.startswith('webroot/') and n.endswith('.js') for n in names), f'{archive}: missing WebUI JS'
        assert any(n.startswith('webroot/') and n.endswith('.css') for n in names), f'{archive}: missing WebUI CSS'
PY
rm -f "$BIN_DIR"/*

(
  cd "$DIST_DIR"
  sha256sum "Magisk-Tailscaled-${VERSION}.zip" "Magisk-Tailscaled-${VERSION}-full.zip" >SHA256SUMS
)
tests/test-package.sh "$VERSION"

ls -lh "$DIST_DIR"
echo "Created $LIGHT and $FULL"
