#!/usr/bin/env bash
set -euo pipefail

VERSION="${1:-$(grep '^version=' module.prop | cut -d'=' -f2)}"
DIST_DIR="dist"
BIN_DIR="tailscale/bin"
MANIFEST="tailscale/binary-manifest.sh"

get_latest_release_json() { curl -fsSL "https://api.github.com/repos/$1/releases/latest"; }
asset_url() { jq -r --arg pattern "$1" '.assets[] | select(.name | test($pattern)) | .browser_download_url' | head -1; }
sha256_file() { sha256sum "$1" | awk '{print $1}'; }
zip_dir() {
  local out="$1"; shift
  python3 - "$out" "$@" <<'PY'
import os, sys, zipfile, fnmatch
out=sys.argv[1]; excludes=sys.argv[2:]
def skip(path):
    return any(fnmatch.fnmatch(path, pat) or path.startswith(pat.rstrip('*')) for pat in excludes)
with zipfile.ZipFile(out, 'w', zipfile.ZIP_DEFLATED, compresslevel=9) as z:
    for root, dirs, files in os.walk('.'):
        dirs[:] = [d for d in dirs if not skip(os.path.relpath(os.path.join(root,d), '.') + '/')]
        for f in files:
            p=os.path.relpath(os.path.join(root,f), '.')
            if p == out or skip(p): continue
            z.write(p)
PY
}

echo "Building Magisk-Tailscaled ${VERSION}"
mkdir -p "$BIN_DIR" "$DIST_DIR"
rm -f "$BIN_DIR"/* "$MANIFEST"

if [ -d webui ] && command -v npm >/dev/null 2>&1; then
  echo "Building KernelSU/APatch WebUI..."
  rm -rf webroot
  npm --prefix webui ci
  npm --prefix webui run build
fi

TS_JSON=$(get_latest_release_json "anasfanani/tailscale-android-cli")
JQ_JSON=$(get_latest_release_json "theshoqanebi/jq-build-for-android")
TS_TAG=$(jq -r .tag_name <<<"$TS_JSON")
JQ_TAG=$(jq -r .tag_name <<<"$JQ_JSON")
{
  echo "# Generated by .github/tools/build.sh for reproducible lightweight installs."
  echo "TAILSCALE_RELEASE_TAG='$TS_TAG'"
  echo "JQ_RELEASE_TAG='$JQ_TAG'"
} > "$MANIFEST"

echo "Downloading and hashing binaries..."
for ARCH in arm arm64; do
  case $ARCH in arm) F_ARCH='armv7a' ;; arm64) F_ARCH='aarch64' ;; esac
  TS_URL=$(jq -r --arg pattern "tailscale_.*_${ARCH}\\.tgz" '.assets[] | select(.name | test($pattern)) | .browser_download_url' <<<"$TS_JSON" | head -1)
  JQ_URL=$(jq -r --arg pattern "jq-${F_ARCH}-linux-android" '.assets[] | select(.name | test($pattern)) | .browser_download_url' <<<"$JQ_JSON" | head -1)
  [ -n "$TS_URL" ] && [ "$TS_URL" != null ] || { echo "missing tailscale asset for $ARCH" >&2; exit 1; }
  [ -n "$JQ_URL" ] && [ "$JQ_URL" != null ] || { echo "missing jq asset for $ARCH" >&2; exit 1; }
  curl -fsSL "$TS_URL" -o "$DIST_DIR/tailscale-$ARCH.tgz"
  curl -fsSL "$JQ_URL" -o "$BIN_DIR/jq-$ARCH"
  tar -xzf "$DIST_DIR/tailscale-$ARCH.tgz" -C "$BIN_DIR" tailscaled
  mv "$BIN_DIR/tailscaled" "$BIN_DIR/tailscaled-$ARCH"
  TS_SHA=$(sha256_file "$DIST_DIR/tailscale-$ARCH.tgz")
  JQ_SHA=$(sha256_file "$BIN_DIR/jq-$ARCH")
  {
    echo "TAILSCALE_${ARCH}_URL='$TS_URL'"
    echo "TAILSCALE_${ARCH}_SHA256='$TS_SHA'"
    echo "JQ_${ARCH}_URL='$JQ_URL'"
    echo "JQ_${ARCH}_SHA256='$JQ_SHA'"
  } >> "$MANIFEST"
done
rm -f "$DIST_DIR"/tailscale-*.tgz

LIGHT="${DIST_DIR}/Magisk-Tailscaled-${VERSION}.zip"
FULL="${DIST_DIR}/Magisk-Tailscaled-${VERSION}-full.zip"
rm -f "$LIGHT" "$FULL"
echo "Creating lightweight zip..."
zip_dir "$LIGHT" '.git*' 'dist/*' '*.zip' '*.md' 'tailscale/bin/*' '.shellcheckrc' 'webui/node_modules/*' 'webui/.parcel-cache/*' 'system/*'
echo "Creating full zip..."
zip_dir "$FULL" '.git*' 'dist/*' '*.zip' '*.md' '.shellcheckrc' 'webui/node_modules/*' 'webui/.parcel-cache/*' 'system/*'
rm -f "$BIN_DIR"/*

ls -lh "$DIST_DIR"
echo "Created $LIGHT and $FULL"
